### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by d11wtq** [turbolent/ralph#8]
Brilliant! :D Ralph looks really interesting. I've been looking for a JS implementation of a (modern) Lisp-1 for quite some time.

Is there any documentation anywhere, besides what's in the README and what can be gleaned from reading the source code?

I guess a few things I'd be looking for documentation on:

  * How does Ralph interoperate with native JS code?
  * Is tail call optimization implemented?
  * Are macros implemented?
  * Any available reader macros that aren't shown in the README?

**Comment by turbolent** [comment]
Hi Chris, thanks for your interest and sorry for the late reply.

I just added a bit more info to the README. It's not exactly documentation,
but I hope it will at least answer your questions. 

Basic tail-call optimization was implemented at some point,
but it wasn't high priority and just too much effort 
(esp. for mutual recursion).

Please let me know if there are still open questions or if you have further ones.
